### ISSUE TITLE
Mixed up names in axi modules (e.g Manager vs Master)

### ISSUE THREAD

**Issue by manikantaallam** [Stuart-Swan/Matchlib-Examples-Kit-For-Accellera-Synthesis-WG#1]
Hi Stuart Swan, Seems like the unittests in cmod are still named master and slave. Regards

**Comment by Stuart-Swan** [comment]
I think that should be fixed now.
Thanks

**Comment by Stuart-Swan** [comment]
I think that should be fixed now.
Thanks
